[package]
name = "depo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
depo = { git = "https://github.com/BlockchainCommons/bc-depo-rust.git" }

[lib]
name = "depo"
path = "depo.rs"
