[package]
name = "torgap"
version = "0.1.0"
edition = "2021"

[dependencies]
bc-server-api = { path = "../../bc-server-api" }
bytes = "1.5.0"
warp = "0.3"
anyhow = "1.0"
log = "0.4.20"
nu-ansi-term = "0.49.0"

